### ISSUE TITLE
How to test other images?

### ISSUE THREAD

**Issue by Chris-lyc** [oneThousand1000/HairMapper#18]
Dear authors, in the step1 of Testing, whether I can only use the align code in the link you provide (image align code) ? I use the code in your link to crop my real images, but for some real images shot from specular angles, the part of head would be cut off. If I use other align code, whether it will affect the HairMapper?

**Comment by oneThousand1000** [comment]
> Dear authors, in the step1 of Testing, whether I can only use the align code in the link you provide (image align code) ? I use the code in your link to crop my real images, but for some real images shot from specular angles, the part of head would be cut off. If I use other align code, whether it will affect the HairMapper?

Hi, the inputting images **must** be aligned according to the function from the original FFHQ dataset, since the StyleGAN model we used in HairMapper is trained on the original FFHQ dataset. Any align code that complies with the alignment function could work.

I am sorry that StyleGAN can not process the full head image, so does our HairMapper, since the alignment function in FFHQ dataset did not take the full head into consideration.
A detailed description of the alignment function can be found in section 4 of the paper "FreeStyleGAN: Free-view Editable Portrait Rendering with the Camera Manifold".

**Comment by Chris-lyc** [comment]
> > Dear authors, in the step1 of Testing, whether I can only use the align code in the link you provide (image align code) ? I use the code in your link to crop my real images, but for some real images shot from specular angles, the part of head would be cut off. If I use other align code, whether it will affect the HairMapper?
> 
> Hi, the inputting images **must** be aligned according to the function from the original FFHQ dataset, since the StyleGAN model we used in HairMapper is trained on the original FFHQ dataset. Any align code that complies with the alignment function could work.
> 
> I am sorry that StyleGAN can not process the full head image, so does our HairMapper, since the alignment function in FFHQ dataset did not take the full head into consideration. A detailed description of the alignment function can be found in section 4 of the paper "FreeStyleGAN: Free-view Editable Portrait Rendering with the Camera Manifold".

Okkk Thank you very much!
