### ISSUE TITLE
weird testing results: real images should be processed by image alignment

### ISSUE THREAD

**Issue by Chopin68** [oneThousand1000/HairMapper#2]
Hi ,
Does this situation need to be solved through training? If so, how can I prepare a data set about her bald head
![C (181)](https://user-images.githubusercontent.com/75252160/165005771-10f3245e-9e2d-4898-b69f-8b483a18ebfa.png)

**Comment by oneThousand1000** [comment]
> Hi ,
> Does this situation need to be solved through training? If so, how can I prepare a data set about her bald head
> ![C (181)](https://user-images.githubusercontent.com/75252160/165005771-10f3245e-9e2d-4898-b69f-8b483a18ebfa.png)

Hi, could you upload the input image and tell me the resolution of it?

Btw, did you process the input image with "image align code" that mentioned in readme?

**Comment by oneThousand1000** [comment]
> Hi ,
> Does this situation need to be solved through training? If so, how can I prepare a data set about her bald head
> ![C (181)](https://user-images.githubusercontent.com/75252160/165005771-10f3245e-9e2d-4898-b69f-8b483a18ebfa.png)

Is it the result of testing? Or you get the bald child image during training?

**Comment by Chopin68** [comment]
> > 你好，
> > 这种情况需要通过培训解决吗？如果是这样，我如何准备一个关于她光头的数据集
> > ![丙 (181)](https://user-images.githubusercontent.com/75252160/165005771-10f3245e-9e2d-4898-b69f-8b483a18ebfa.png)
> 
> 嗨，你能上传输入图像并告诉我它的分辨率吗？
> 
> 顺便说一句，您是否使用自述文件中提到的“图像对齐代码”处理输入图像？

The resolution is 512x512
![C (181)](https://user-images.githubusercontent.com/75252160/165011434-7000384f-9daf-4df2-b597-13574c1f44a5.jpg)

I didn't do image alignment, but I used 1024x1024 and succeeded in several cases, but sometimes bald child still appear.

**Comment by Chopin68** [comment]
This is the result of the test. I haven't trained yet because I don't know how to collect some bald data sets to fit her.

**Comment by oneThousand1000** [comment]
> This is the result of the test. I haven't trained yet because I don't know how to collect some bald data sets to fit her.

As I explained in the readme, you should ** do image alignment first ** (the input image will be automatically clipped and resized to 1024x1024 ) then apply encoder4editing to obtain latent code, finally run our HairMapper.

The image alignment is only required in the testing stage, and there is no need to collect your own bald datasets because all the training images are generated by StyleGAN.

I applied image alignment to your input image:
![test_01](https://user-images.githubusercontent.com/32099648/165012470-723bd53a-954b-4421-9270-9c23d5add73c.png)

I get the result:
![test_01](https://user-images.githubusercontent.com/32099648/165012773-892600ff-553c-4a2b-a9b3-d4bb72d92a33.png)

**Comment by Chopin68** [comment]
Thank you for your guidance! I already know how to get a normal result.
