### ISSUE TITLE
more about blending the clean face with some hairstyle templates

### ISSUE THREAD

**Issue by onefish51** [oneThousand1000/HairMapper#5]
good work !

Can you tell more about blending the clean face with some hairstyle templates ?

It's a funny work

**Comment by oneThousand1000** [comment]
> good work !
> 
> Can you tell more about blending the clean face with some hairstyle templates ?
> 
> It's a funny work

Hi onefish51! 
In fig. 1 of our paper, we extract the hairstyle template from images in FFHQ (using the faceparsing to generate the hair mask) and apply Poisson editing to blend the hair with the clean face.
Btw, the image that provides the hairstyle template should have a similar face posture with the clean face (we select the templates manually), since we only simply copy and paste the hairstyle template without any warping.

**Comment by oneThousand1000** [comment]
I can upload our ''add hair'' code for your reference, but I didn't check it :), so you need to modify it according to your own data path.
[add_hair.zip](https://github.com/oneThousand1000/HairMapper/files/8657306/add_hair.zip)

Good luck!

**Comment by onefish51** [comment]
Thank you for the quick reply！having a try !

By the way, why not hair change by StyleCLIP instead of hair removal and paste hairstyle template ?

**Comment by oneThousand1000** [comment]
> Thank you for the quick reply！having a try !
> 
> By the way, why not hair change by StyleCLIP instead of hair removal and paste hairstyle template ?

In fact, StyleGAN isn't very excellent at creating hairstyles. Our goal is to remove hair from portraits so that people can add hair in whichever way they choose (3d rendering, GANs, .......)

**Comment by onefish51** [comment]
I see! thanks !

**Comment by sunzongzheng** [comment]
@oneThousand1000 did you fingure out any idea for better blending with the clean face and hair?

I used the add_hair.py, but the effect is not very good in most scenes. As you said above, we may need to warp and align the hair to make the blending effect better.
